### ISSUE TITLE
Linking CSS and JS?

### ISSUE THREAD

**Issue by tomkcey** [rjoonas/heroku-docker-nginx-example#4]
Greetings,

I used this to launch my first static web page, but I have CSS that doesn't seem to connect. How would I go about linking it?

--static-html
----src
------assets
--------something.css
------something.js
----index.html

Both are linked using relative path, in the index.html.

**Comment by rjoonas** [comment]
Hi @tomkcey, sounds like a markup problem unrelated to nginx or this Dockerfile.

That folder structure works for me with an `index.html` file like

```html
<html>
  <head>
    <link rel="stylesheet" href="src/assets/something.css" />
  </head>
  <body>
    <p>Hello from Nginx on Heroku!</p>
  </body>
  <script src="src/something.js"></script>
</html>
```

Remember to `heroku container:push web` + `heroku container:release web`. Next thing I would do if using nginx to serve static files would be to configure MIME types.

**Comment by tomkcey** [comment]
Yeah, I was able to find the solution in the end. Thanks for taking the time!
