### ISSUE TITLE
Include mime.types in nginx.conf

### ISSUE THREAD

**Issue by unmade** [rjoonas/heroku-docker-nginx-example#5]
Greetings!

Thanks for a good example! 

I've noticed that `nginx.conf` doesn't include mime.types and because of that css styles may not be loaded correctly, also browser console gives this error:
```Resource interpreted as Stylesheet but transferred with MIME type text/plain```

For example, this will fix the problem:
```
# nginx.conf
http {
    include       /etc/nginx/mime.types;
    ...
}
```

**Comment by rjoonas** [comment]
Hi! I'm trying to keep the example as barebones as possible so people can write their own config on top with minimal cruft to be deleted first. All use cases don't need to serve static assets directly, eg. if you're only using nginx for serving redirects or as a reverse proxy.

Maybe stuff like this could go in the README? We could have sort of a ”what's next” section pointing to some example configs or tutorials for common use cases.

**Comment by unmade** [comment]
Oh, I see your point!
"What's next" is a good idea, however, I think stuff like that is pretty easy to figure out yourself. I just didn't think this line was missing on purpose, when copy-paste the example :)
